#:package Confluent.Kafka@2.12.0


#:property JsonSerializerIsReflectionEnabledByDefault=true
#:property PublishTrimmed=false

using System.Text.Encodings.Web;
using System.Text.Json;
using System.Text.Json.Serialization.Metadata;
using Confluent.Kafka;

// 创建 options 实例
var options = new JsonSerializerOptions
{
    // 显式地将解析器设置为默认的（基于反射的）解析器
    TypeInfoResolver = new DefaultJsonTypeInfoResolver(),
    Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping,
    // 您可以添加其他选项，如 Indented = true 等
};


Random rnd = new();

var kafka = (int index) =>
$$""""
{
    "box_num": 1,
    "current_station": 2,
    "dDevice": 50,
    "dataParam": {
        "cknj": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cknk": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cknh": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "ckni": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cknf": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "ckng": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "ckms": 0,
        "ckmt": 0,
        "ckmq": 0,
        "ckmr": 0,
        "ckmo": 0,
        "ckmp": 0,
        "ckmm": 0,
        "ckmn": 0,
        "ckmk": 0,
        "ckml": 0,
        "ckmj": 0,
        "ckme": 0,
        "cknd": 19.2,
        "ckne": 18.7,
        "cknb": 0,
        "cknc": 0,
        "ckna": 0,
        "ckmy": 0,
        "ckmz": 0,
        "ckmw": 0,
        "ckmx": 0,
        "ckmu": 0,
        "ckmv": 0,
        "ckpv": 0,
        "ckpw": 0,
        "ckpt": 0,
        "ckpu": 0,
        "ckpr": 0,
        "ckps": 0,
        "ckpp": 0,
        "ckpq": 0,
        "ckpn": 0,
        "ckpo": 0,
        "ckpl": 0,
        "ckpm": 0,
        "ckpj": 0,
        "ckpk": 0,
        "ckph": 0,
        "ckpi": 0,
        "ckqg": 0,
        "ckqh": 0,
        "ckqe": 0,
        "ckqf": 0,
        "ckqc": 0,
        "ckqd": 0,
        "ckqa": 0,
        "ckqb": 0,
        "ckpz": 0,
        "ckpx": 0,
        "ckpy": 0,
        "ckou": 0,
        "ckov": 0,
        "ckot": 0,
        "ckoo": 0,
        "ckop": 0,
        "ckom": 0,
        "ckon": 1,
        "ckoj": 0,
        "ckpf": 0,
        "ckpg": 0,
        "ckpd": 0,
        "ckpc": 0,
        "ckpa": 0,
        "ckoy": 0,
        "ckoz": 0,
        "ckow": 0,
        "ckox": 0,
        "ckrx": 0,
        "ckry": 0,
        "ckrv": 0,
        "ckrw": 0,
        "ckrt": 0,
        "ckru": 0,
        "ckrr": 0,
        "ckrs": 0,
        "ckrp": 0,
        "ckrq": 0,
        "ckrn": 0,
        "ckro": 0,
        "ckrl": 0,
        "ckrm": 0,
        "ckrj": 0,
        "ckrk": 0,
        "cksi": 0,
        "cksg": 0,
        "ckse": 0,
        "cksf": 0,
        "cksc": 0,
        "cksd": 0,
        "cksa": 0,
        "cksb": 0,
        "ckrz": 0,
        "ckqw": 0,
        "ckqx": 0,
        "ckqu": 0,
        "ckqv": 0,
        "ckqs": 0,
        "ckqt": 0,
        "ckqq": 0,
        "ckqr": 0,
        "ckqo": 0,
        "ckqp": 0,
        "ckqm": 0,
        "ckqn": 0,
        "ckqk": 0,
        "ckql": 0,
        "ckqi": 0,
        "ckqj": 0,
        "ckrh": 0,
        "ckri": 0,
        "ckrf": 0,
        "ckrg": 0,
        "ckrd": 0,
        "ckre": 0,
        "ckrb": 0,
        "ckrc": 0,
        "ckra": 0,
        "ckqy": 0,
        "ckqz": 0,
        "cktz": 0,
        "cktx": 0,
        "ckty": 0,
        "cktv": 0,
        "cktw": 0,
        "cktt": 0,
        "cktu": 0,
        "cktr": 0,
        "ckts": 0,
        "cktp": 0,
        "cktq": 0,
        "cktn": 0,
        "ckto": 0,
        "cktl": 0,
        "cktm": 0,
        "ckuk": 0,
        "ckul": 0,
        "ckui": 0,
        "ckuj": 0,
        "ckug": 0,
        "ckuh": 0,
        "ckue": 0,
        "ckuf": 0,
        "ckuc": 0,
        "ckud": 0,
        "ckua": 0,
        "ckub": 0,
        "cksy": 0,
        "cksw": 0,
        "cksx": 0,
        "cksu": 0,
        "cksv": 0,
        "cksq": 0,
        "ckso": 0,
        "cksp": 0,
        "cksm": 0,
        "cksn": 0,
        "cktk": 0,
        "cktf": 0,
        "cktg": 0,
        "cktd": 0,
        "ckte": 0,
        "cktc": 0,
        "ckvz": 0,
        "ckvx": 0,
        "ckvy": 1,
        "ckwm": 0,
        "ckwn": 0,
        "ckwk": 0,
        "ckwl": 0,
        "ckwi": 0,
        "ckwj": 0,
        "ckwh": 0,
        "ckwf": 0,
        "ckwd": 0,
        "ckwb": 0,
        "ckuy": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "ckuz": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "ckuw": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "ckux": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "ckuu": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "ckuv": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "ckus": 0,
        "ckut": 0,
        "ckuq": 0,
        "ckur": 0,
        "ckuo": 0,
        "ckup": 0,
        "ckum": 0,
        "ckun": 0,
        "ckvj": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "ckvh": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "ckvi": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "ckvf": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "ckvg": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "ckvd": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "ckve": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "ckvb": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "ckvc": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "ckva": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "ckxz": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "ckxx": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "ckxy": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "ckxv": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "ckxw": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "ckxt": 0,
        "ckxu": 0,
        "ckxr": 0,
        "ckxs": 0,
        "ckxp": 0,
        "ckxq": 0,
        "ckyc": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "ckyd": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "ckya": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "ckyb": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "ckww": 0,
        "ckwx": 0,
        "ckwu": 0,
        "ckwv": 0,
        "ckws": 0,
        "ckwt": 0,
        "ckwq": 0,
        "ckwr": 0,
        "ckwo": 0,
        "ckwp": 0,
        "ckxn": 0,
        "ckxo": 0,
        "ckxl": 0,
        "ckxm": 0,
        "ckxj": 0,
        "ckxk": 0,
        "ckxh": 0,
        "ckxi": 0,
        "ckxf": 0,
        "ckxg": 0,
        "ckxd": 0,
        "ckxe": 0,
        "ckxc": 0,
        "ckzz": 0,
        "ckzy": 0,
        "ckzv": 0,
        "ckzw": 0,
        "ckzt": 0,
        "ckzr": 0,
        "ckzs": 0,
        "ckzp": 0,
        "ckzq": 0,
        "ckzn": 0,
        "ckzo": 0,
        "ckzm": 0,
        "ckzh": 0,
        "ckzi": 0,
        "ckzf": 0,
        "ckzg": 1,
        "ckzc": 0,
        "clbg": 0,
        "clbh": 0,
        "clbe": 0,
        "clbf": 0,
        "clbc": 0,
        "clbd": 0,
        "clba": 0,
        "clbb": 0,
        "claz": 0,
        "clax": 0,
        "clay": 0,
        "clbw": 0,
        "clbx": 0,
        "clbu": 0,
        "clbv": 0,
        "clbs": 0,
        "clbt": 0,
        "clbq": 0,
        "clbr": 0,
        "clbo": 0,
        "clbp": 0,
        "clbm": 0,
        "clbn": 0,
        "clbk": 0,
        "clbl": 0,
        "clbi": 0,
        "clbj": 0,
        "claf": 0,
        "clag": 0,
        "clad": 0,
        "clae": 0,
        "clab": 0,
        "clac": 0,
        "claa": 0,
        "clav": 0,
        "claw": 0,
        "clat": 0,
        "clau": 0,
        "clar": 0,
        "clas": 0,
        "clap": 0,
        "claq": 0,
        "clan": 0,
        "clao": 0,
        "clal": 0,
        "clam": 0,
        "claj": 0,
        "clak": 0,
        "clah": 0,
        "clai": 0,
        "cldi": 0,
        "cldj": 0,
        "cldg": 0,
        "cldh": 0,
        "cldf": 0,
        "cldb": 0,
        "clcz": 0,
        "cldy": 0,
        "cldz": 0,
        "cldw": 0,
        "cldx": 0,
        "cldv": 0,
        "cldq": 0,
        "cldr": 0,
        "cldo": 0,
        "cldp": 0,
        "cldn": 0,
        "clch": 0,
        "clci": 0,
        "clcf": 0,
        "clcg": 0,
        "clcd": 0,
        "clce": 0,
        "clcb": 0,
        "clcc": 0,
        "clca": 0,
        "clby": 0,
        "clbz": 0,
        "clcx": 0,
        "clcy": 0,
        "clcv": 0,
        "clcw": 0,
        "clct": 0,
        "clcu": 0,
        "clcr": 0,
        "clcs": 0,
        "clcp": 0,
        "clcq": 0,
        "clcn": 0,
        "clco": 0,
        "clcl": 0,
        "clcm": 0,
        "clcj": 0,
        "clck": 0,
        "clfk": 0,
        "clfl": 0,
        "clfi": 0,
        "clfj": 0,
        "clfg": 0,
        "clfh": 0,
        "clfe": 0,
        "clff": 0,
        "clfc": 0,
        "clfd": 0,
        "clfa": 0,
        "clfb": 0,
        "clfy": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "clfz": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "clfw": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "clfx": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "clfu": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "clfv": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "clfs": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "clft": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "clfq": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "clfr": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "clfo": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "clfp": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "clfm": 0,
        "clfn": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "clej": 0,
        "clek": 0,
        "cleh": 0,
        "clei": 0,
        "clef": 0,
        "cleg": 0,
        "cled": 0,
        "clee": 0,
        "clez": 0,
        "clex": 0,
        "cley": 0,
        "clev": 0,
        "clew": 0,
        "clet": 0,
        "cleu": 0,
        "cler": 0,
        "cles": 0,
        "clep": 0,
        "cleq": 0,
        "clen": 0,
        "cleo": 0,
        "clel": 0,
        "clem": 0,
        "clhm": 0,
        "clhn": 0,
        "clhk": 0,
        "clhl": 0,
        "clhi": 0,
        "clhj": 0,
        "clhg": 0,
        "clhh": 0,
        "clhe": 0,
        "clhf": 0,
        "clhc": 0,
        "clhd": 0,
        "clha": 0,
        "clhb": 0,
        "clhy": 0,
        "clhz": 0,
        "clhw": 0,
        "clhx": 0,
        "clhv": 0,
        "clhq": 0,
        "clho": 0,
        "clhp": 0,
        "clgb": 18.2,
        "clgc": 18.3,
        "clga": 18.7,
        "clgy": 0,
        "clgw": 0,
        "clgu": 0,
        "clgr": 1,
        "clgs": 0,
        "clgq": 0,
        "clka": 0,
        "cljy": 0,
        "cljz": 1,
        "cljv": 0,
        "cljt": 0,
        "clin": 0,
        "clio": 0,
        "clil": 0,
        "clim": 0,
        "clij": 0,
        "clik": 0,
        "clih": 0,
        "clii": 0,
        "clif": 0,
        "clig": 0,
        "clid": 0,
        "clie": 0,
        "clib": 0,
        "clic": 0,
        "clia": 0,
        "cliv":{{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cliw": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "clit": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cliu": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "clir": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "clis": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "clip": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cliq": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cllq": 0,
        "cllr": 0,
        "cllo": 0,
        "cllp": 0,
        "cllm": 0,
        "clln": 0,
        "cllk": 0,
        "clll": 0,
        "clli": 0,
        "cllj": 0,
        "cllh": 0,
        "clmb": 0,
        "clmc": 0,
        "clma": 0,
        "clly": 0,
        "cllz": 0,
        "cllw": 0,
        "cllx": 0,
        "cllu": 0,
        "cllv": 0,
        "clls": 0,
        "cllt": 0,
        "clkp": 0,
        "clko": 0,
        "clkl": 0,
        "clkm": 0,
        "clkh": 0,
        "clki": 0,
        "clkb": 0,
        "clkx": 0,
        "clky": 0,
        "clkv": 0,
        "clkw": 0,
        "clkt": 0,
        "clku": 0,
        "clkr": 0,
        "clks": 0,
        "clns": 0,
        "clnq": 0,
        "clnr": 0,
        "clno": 0,
        "clnp": 0,
        "clnm": 0,
        "clnn": 0,
        "clnk": 0,
        "clnl": 0,
        "clni": 0,
        "clnj": 0,
        "clng": 0,
        "clnh": 0,
        "clne": 0,
        "clnf": 0,
        "clmr": 0,
        "clms": 0,
        "clmp": 0,
        "clmq": 0,
        "clmn": 0,
        "clmo": 0,
        "clml": 0,
        "clmm": 0,
        "clmj": 0,
        "clmk": 0,
        "clmh": 0,
        "clmi": 0,
        "clmf": 0,
        "clmg": 0,
        "clmd": 0,
        "clme": 0,
        "clnc": 0,
        "clnd": 0,
        "clna": 0,
        "clnb": 0,
        "clmz": 0,
        "clmx": 0,
        "clmy": 0,
        "clmv": 0,
        "clmw": 0,
        "clmt": 0,
        "clmu": 0,
        "clqg": 18.6,
        "clrx": 0,
        "clrv": 0,
        "clrs": 1,
        "clrt": 0,
        "clrr": 0,
        "clsh": 0,
        "clsi": 0,
        "clsf": 0,
        "clsg": 0,
        "clsd": 0,
        "clse": 0,
        "clsb": 0,
        "clsc": 0,
        "clrz": 0,
        "clqn": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "clql": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "clqm": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "clqj": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "clqk": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "clqh": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "clqi": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cltu": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cltv": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "club": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "clua": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "clsy": 0,
        "clsj": 0,
        "cltg": 0,
        "clth": 0,
        "clte": 0,
        "cltf": 0,
        "cltc": 0,
        "cltd": 0,
        "clta": 0,
        "cltb": 0,
        "clsz": 0,
        "clvs": 2,
        "clvt": 24,
        "clvq": 2,
        "clvr": 2,
        "clvo": 840,
        "clvp": 840,
        "clvm": 840,
        "clvn": 840,
        "cluz": 35.6,
        "clux": 22,
        "cluy": 0,
        "cluv": 13,
        "cluw": 13,
        "clut": 12,
        "cluu": 12,
        "clur": 6037,
        "clus": 25,
        "clvk": 840,
        "clvl": 840,
        "clvi": 0,
        "clvj": 0,
        "clvg": 0,
        "clvh": 0,
        "clve": 35.6,
        "clvf": 225.6,
        "clvc": 38.2,
        "clvd": 39,
        "clva": 39,
        "clvb": 38.2,
        "cmbp": 1,
        "cmbq": 1,
        "cmbn": 1,
        "cmbo": 1,
        "cmbl": 1,
        "cmbm": 1,
        "cmbj": 1,
        "cmbk": 1,
        "cmbh": 2934,
        "cmbi": "2.0.11",
        "cmdd": 0,
        "cmdb": 0,
        "cmdc": 0,
        "cmda": 0,
        "cmcy": 0,
        "cmcz": 0,
        "cmdx": 0,
        "cmdy": 0,
        "cmdv": 0,
        "cmdw": 0,
        "cmdt": 0,
        "cmdu": 0,
        "cmdr": 0,
        "cmds": 0,
        "cmdp": 0,
        "cmdq": 0,
        "cmdn": 0,
        "cmdo": 0,
        "cmdm": 0,
        "cmcg": 0,
        "cmch": 1,
        "cmce": 1,
        "cmcf": 0,
        "cmcd": 0,
        "cmby": 0,
        "cmcw": 0,
        "cmcx": 0,
        "cmcu": 0,
        "cmct": 0,
        "cmcq": 0,
        "cmcr": 0,
        "cmcm": 0,
        "cmcn": 0,
        "cmfj": 0,
        "cmfk": 0,
        "cmfh": 0,
        "cmfi": 0,
        "cmff": 0,
        "cmfg": 0,
        "cmfd": 0,
        "cmfe": 0,
        "cmfb": 0,
        "cmfc": 0,
        "cmfa": 0,
        "cmfx": 0,
        "cmfv": 0,
        "cmfw": 0,
        "cmft": 0,
        "cmfu": 0,
        "cmfr": 0,
        "cmfs": 0,
        "cmfp": 0,
        "cmfq": 0,
        "cmfn": 0,
        "cmfo": 0,
        "cmfl": 0,
        "cmfm": 0,
        "cmei": 0,
        "cmej": 0,
        "cmeg": 0,
        "cmeh": 0,
        "cmee": 0,
        "cmef": 0,
        "cmec": 0,
        "cmed": 0,
        "cmea": 0,
        "cmeb": 0,
        "cmdz": 0,
        "cmey": 0,
        "cmez": 0,
        "cmew": 0,
        "cmex": 0,
        "cmeu": 0,
        "cmev": 0,
        "cmes": 0,
        "cmet": 0,
        "cmeq": 0,
        "cmer": 0,
        "cmeo": 0,
        "cmep": 0,
        "cmem": 0,
        "cmen": 0,
        "cmek": 0,
        "cmel": 0,
        "cmjx": 1,
        "cmjy": 0,
        "cmjw": 0,
        "cmim": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cmin": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cmil": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cmis": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cmiq": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cmir": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cmio": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cmip": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cmll": 0,
        "cmlm": 0,
        "cmlj": 0,
        "cmlk": 0,
        "cmlh": 0,
        "cmli": 0,
        "cmlf": 0,
        "cmlg": 0,
        "cmld": 0,
        "cmle": 0,
        "cmma": 20.1,
        "cmlz": 20.1,
        "cmko": 0,
        "cmkm": 0,
        "cmkn": 0,
        "cmkk": 0,
        "cmkl": 0,
        "cmki": 0,
        "cmkj": 0,
        "cmkg": 0,
        "cmkh": 0,
        "cmke": 0,
        "cmkc": 0,
        "cmka": 0,
        "cmnr": 0,
        "cmns": 0,
        "cmnp": 0,
        "cmnq": 0,
        "cmnl": 0,
        "cmnj": 1,
        "cmnk": 0,
        "cmni": 0,
        "cmnf": 0,
        "cmoc": 0,
        "cmod": 0,
        "cmob": 0,
        "cmnz": 0,
        "cmny": 0,
        "cmnv": 0,
        "cmnw": 0,
        "cmnt": 0,
        "cmnu": 0,
        "cmmg": 37.1,
        "cmmf": 37.7,
        "cmpt": 0,
        "cmpu": 0,
        "cmpr": 0,
        "cmps": 0,
        "cmpp": 0,
        "cmpq": 0,
        "cmpn": 0,
        "cmpo": 0,
        "cmpl": 0,
        "cmpm": 0,
        "cmpj": 0,
        "cmpk": 0,
        "cmph": 0,
        "cmpi": 0,
        "cmpf": 0,
        "cmpg": 0,
        "cmqe": 0,
        "cmqf": 0,
        "cmqc": 0,
        "cmqd": 0,
        "cmqa": 0,
        "cmqb": 0,
        "cmpz": 0,
        "cmpx": 0,
        "cmpy": 0,
        "cmpv": 0,
        "cmpw": 0,
        "cmos": 0,
        "cmot": 0,
        "cmoq": 0,
        "cmor": 0,
        "cmoo": 0,
        "cmop": 0,
        "cmom": 0,
        "cmon": 0,
        "cmok": 0,
        "cmol": 0,
        "cmoi": 0,
        "cmoj": 0,
        "cmog": 0,
        "cmoh": 0,
        "cmoe": 0,
        "cmof": 0,
        "cmpd": 0,
        "cmpe": 0,
        "cmpb": 0,
        "cmpc": 0,
        "cmpa": 0,
        "cmoy": 0,
        "cmoz": 0,
        "cmow": 0,
        "cmox": 0,
        "cmou": 0,
        "cmov": 0,
        "cmrt": 0,
        "cmru": 0,
        "cmrr": 0,
        "cmrs": 0,
        "cmrq": 0,
        "cmrl": 0,
        "cmrm": 0,
        "cmrj": 0,
        "cmrk": 0,
        "cmri": 0,
        "cmsg": 0,
        "cmsh": 0,
        "cmsc": 0,
        "cmsa": 0,
        "cmsb": 0,
        "cmrz": 0,
        "cmry": 0,
        "cmqu": 0,
        "cmqv": 0,
        "cmqs": 0,
        "cmqt": 0,
        "cmqq": 0,
        "cmqr": 0,
        "cmqo": 0,
        "cmqp": 0,
        "cmqm": 0,
        "cmqn": 0,
        "cmqk": 0,
        "cmql": 0,
        "cmqi": 0,
        "cmqj": 0,
        "cmqg": 0,
        "cmqh": 0,
        "cmre": 0,
        "cmrb": 0,
        "cmrc": 0,
        "cmra": 0,
        "cmqy": 0,
        "cmqz": 0,
        "cmqw": 0,
        "cmqx": 0,
        "cmtx": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cmty": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cmtv": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cmtw": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cmtt": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cmtu": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cmtr": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cmts": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cmtp": 0,
        "cmtq": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cmtn": 0,
        "cmto": 0,
        "cmtl": 0,
        "cmtm": 0,
        "cmtj": 0,
        "cmtk": 0,
        "cmue": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cmuf": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cmuc": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cmud": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cmua": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cmub": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cmtz": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cmsw": 0,
        "cmsx": 0,
        "cmsu": 0,
        "cmsv": 0,
        "cmss": 0,
        "cmst": 0,
        "cmsq": 0,
        "cmsr": 0,
        "cmso": 0,
        "cmsp": 0,
        "cmsm": 0,
        "cmsn": 0,
        "cmsk": 0,
        "cmsl": 0,
        "cmsi": 0,
        "cmsj": 0,
        "cmth": 0,
        "cmti": 0,
        "cmtf": 0,
        "cmtg": 0,
        "cmtd": 0,
        "cmte": 0,
        "cmtb": 0,
        "cmtc": 0,
        "cmta": 0,
        "cmsy": 0,
        "cmsz": 0,
        "cmvz": 0,
        "cmvy": 0,
        "cmvt": 0,
        "cmvr": 0,
        "cmvs": 0,
        "cmvp": 0,
        "cmvq": 0,
        "cmvn": 0,
        "cmvo": 0,
        "cmvl": 0,
        "cmvm": 0,
        "cmwk": 0,
        "cmwl": 0,
        "cmwi": 0,
        "cmwj": 0,
        "cmwg": 0,
        "cmwh": 0,
        "cmwe": 0,
        "cmwf": 0,
        "cmwc": 0,
        "cmwd": 0,
        "cmwa": 0,
        "cmwb": 0,
        "cmuz": 0,
        "cmux": 0,
        "cmuu": 1,
        "cmuv": 0,
        "cmut": 0,
        "cmvj": 0,
        "cmvk": 0,
        "cmvh": 0,
        "cmvi": 0,
        "cmvf": 0,
        "cmvg": 0,
        "cmvd": 0,
        "cmve": 0,
        "cmvb": 0,
        "cmxy": 0,
        "cmym": 0,
        "cmyn": 0,
        "cmyk": 0,
        "cmyl": 0,
        "cmyi": 0,
        "cmyj": 0,
        "cmyh": 0,
        "cmye": 0,
        "cmyc": 1,
        "cmyd": 0,
        "cmyb": 0,
        "cmwy": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cmwz": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cmww": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cmwx": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cmwu": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cmwv": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cmws": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cmwt": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cmwq": 0,
        "cmwr": 0,
        "cmwo": 0,
        "cmwp": 0,
        "cmwm": 0,
        "cmwn": 0,
        "cmzz": 0,
        "cmzx": 0,
        "cmzy": 0,
        "cmzv": 0,
        "cmzw": 0,
        "cmzt": 0,
        "cmzu": 0,
        "cmzr": 0,
        "cmzs": 0,
        "cmzp": 0,
        "cmzq": 0,
        "cmyy": 0,
        "cmyz": 0,
        "cmyw": 0,
        "cmyx": 0,
        "cmyu": 0,
        "cmyv": 0,
        "cmys": 0,
        "cmyr": 0,
        "cmyo": 0,
        "cmyp": 0,
        "cmzn": 0,
        "cmzo": 0,
        "cmzl": 0,
        "cmzm": 0,
        "cmzj": 0,
        "cmzk": 0,
        "cmzh": 0,
        "cmzi": 0,
        "cmzf": 0,
        "cmzg": 0,
        "cmzd": 0,
        "cmze": 0,
        "cmzb": 0,
        "cmzc": 0,
        "cmza": 0,
        "cnbe": 0,
        "cnbf": 0,
        "cnbc": 0,
        "cnbd": 0,
        "cnba": 0,
        "cnbb": 0,
        "cnaz": 0,
        "cnax": 0,
        "cnay": 0,
        "cnav": 0,
        "cnaw": 0,
        "cnbu": 0,
        "cnbv": 0,
        "cnbs": 0,
        "cnbt": 0,
        "cnbq": 0,
        "cnbr": 0,
        "cnbo": 0,
        "cnbp": 0,
        "cnbm": 0,
        "cnbn": 0,
        "cnbk": 0,
        "cnbl": 0,
        "cnbi": 0,
        "cnbj": 0,
        "cnbg": 0,
        "cnbh": 0,
        "cnad": 0,
        "cnae": 0,
        "cnab": 0,
        "cnac": 0,
        "cnaa": 0,
        "cnat": 0,
        "cnau": 0,
        "cnar": 0,
        "cnas": 0,
        "cnap": 0,
        "cnaq": 0,
        "cnan": 0,
        "cnao": 0,
        "cnal": 0,
        "cnam": 0,
        "cnaj": 0,
        "cnak": 0,
        "cnah": 0,
        "cnai": 0,
        "cnaf": 0,
        "cnag": 0,
        "cndg": 0,
        "cndh": 0,
        "cnde": 0,
        "cndf": 0,
        "cndc": 0,
        "cndd": 0,
        "cnda": 0,
        "cndb": 0,
        "cncz": 0,
        "cndw": 0,
        "cndx": 0,
        "cndu": 0,
        "cndv": 0,
        "cnds": 0,
        "cndt": 0,
        "cndq": 0,
        "cndr": 0,
        "cndo": 0,
        "cndp": 0,
        "cndm": 0,
        "cndn": 0,
        "cndk": 0,
        "cndl": 0,
        "cndi": 0,
        "cndj": 0,
        "cncf": 0,
        "cncd": 0,
        "cnce": 0,
        "cncb": 0,
        "cncc": 0,
        "cnbx": 0,
        "cncv": 0,
        "cnct": 0,
        "cncu": 0,
        "cncr": 0,
        "cncs": 0,
        "cncn": 0,
        "cncl": 0,
        "cncm": 0,
        "cncj": 0,
        "cnck": 0,
        "cnfy": 0,
        "cnfz": 0,
        "cnfw": 0,
        "cnfx": 0,
        "cnfu": 0,
        "cnfs": 0,
        "cnfq": 0,
        "cnfo": 0,
        "cnfm": 0,
        "cnfn": 1,
        "cneh": 0,
        "cnei": 0,
        "cnef": 0,
        "cneg": 0,
        "cned": 0,
        "cnee": 0,
        "cneb": 0,
        "cnec": 0,
        "cnea": 0,
        "cndy": 0,
        "cndz": 0,
        "cnex": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cney": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cnev": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cnew": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cnet": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cneu": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cner": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cnes": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cnep": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cneq": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cnen": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cneo": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cnel": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cnem": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cnej": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cnek": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cnhk": 0,
        "cnhl": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cnhi": 0,
        "cnhj": 0,
        "cnhg": 0,
        "cnhh": 0,
        "cnhe": 0,
        "cnhf": 0,
        "cnhc": 0,
        "cnhd": 0,
        "cnha": 0,
        "cnhb": 0,
        "cnhs": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cnhq": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cnhr": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cnho": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cnhp": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cnhm": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cnhn": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cngj": 0,
        "cngk": 0,
        "cngh": 0,
        "cngi": 0,
        "cngf": 0,
        "cngg": 0,
        "cngd": 0,
        "cnge": 0,
        "cngb": 0,
        "cngc": 0,
        "cnga": 0,
        "cngz": 0,
        "cngx": 0,
        "cngy": 0,
        "cngv": 0,
        "cngw": 0,
        "cngt": 0,
        "cngu": 0,
        "cngr": 0,
        "cngs": 0,
        "cngl": 0,
        "cngm": 0,
        "cnjn": 0,
        "cnjk": 0,
        "cnjl": 0,
        "cnji": 0,
        "cnjg": 0,
        "cnjh": 0,
        "cnje": 0,
        "cnjf": 0,
        "cnjc": 0,
        "cnjd": 0,
        "cnjb": 0,
        "cnjy": 0,
        "cnjz": 0,
        "cnjw": 0,
        "cnjx": 0,
        "cnju": 0,
        "cnjv": 0,
        "cnjs": 0,
        "cnjt": 0,
        "cnjq": 0,
        "cnjr": 0,
        "cnjo": 0,
        "cnjp": 0,
        "cnix": 0,
        "cniv": 1,
        "cniw": 0,
        "cniu": 0,
        "cnir": 0,
        "cnlo": 0,
        "cnlp": 0,
        "cnlm": 0,
        "cnln": 0,
        "cnlk": 0,
        "cnll": 0,
        "cnli": 0,
        "cnlj": 0,
        "cnlg": 0,
        "cnlh": 0,
        "cnle": 0,
        "cnlf": 0,
        "cnlc": 0,
        "cnld": 0,
        "cnla": 0,
        "cnlb": 0,
        "cnma": 0,
        "cnly": 0,
        "cnlz": 0,
        "cnlw": 0,
        "cnlx": 0,
        "cnlu": 0,
        "cnlv": 0,
        "cnls": 0,
        "cnlt": 0,
        "cnlq": 0,
        "cnlr": 0,
        "cnkn": 0,
        "cnko": 0,
        "cnkl": 0,
        "cnkm": 0,
        "cnkj": 0,
        "cnkk": 0,
        "cnkh": 0,
        "cnki": 0,
        "cnkf": 0,
        "cnkg": 0,
        "cnkd": 0,
        "cnke": 0,
        "cnkb": 0,
        "cnkc": 0,
        "cnka": 0,
        "cnkz": 0,
        "cnkx": 0,
        "cnky": 0,
        "cnkv": 0,
        "cnkw": 0,
        "cnkt": 0,
        "cnku": 0,
        "cnkr": 0,
        "cnks": 0,
        "cnkp": 0,
        "cnkq": 0,
        "cnno": 0,
        "cnnm": 0,
        "cnnn": 0,
        "cnnk": 0,
        "cnnl": 0,
        "cnng": 0,
        "cnne": 0,
        "cnnf": 0,
        "cnnc": 0,
        "cnnd": 0,
        "cnob": 0,
        "cnoc": 0,
        "cnoa": 0,
        "cnny": 0,
        "cnnz": 0,
        "cnnw": 0,
        "cnnx": 0,
        "cnnu": 0,
        "cnnv": 0,
        "cnns": 0,
        "cnnt": 0,
        "cnmq": 0,
        "cnmn": 0,
        "cnmo": 0,
        "cnml": 0,
        "cnmm": 0,
        "cnmj": 0,
        "cnmk": 0,
        "cnmh": 0,
        "cnmi": 0,
        "cnmf": 0,
        "cnmg": 0,
        "cnmd": 0,
        "cnme": 0,
        "cnmb": 0,
        "cnmc": 0,
        "cnmx": 0,
        "cnmy": 0,
        "cnmv": 0,
        "cnmw": 0,
        "cnmu": 0,
        "cnpq": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cnpr": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cnpo": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cnpp": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cnpm": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cnpn": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cnpk": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cnpl": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cnpi": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cnpj": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cnpg": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cnph": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cnpe": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cnpf": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cnor": 0,
        "cnos": 0,
        "cnop": 0,
        "cnoq": 0,
        "cnon": 0,
        "cnoo": 0,
        "cnol": 0,
        "cnom": 0,
        "cnoj": 0,
        "cnok": 0,
        "cnoh": 0,
        "cnoi": 0,
        "cnof": 0,
        "cnog": 0,
        "cnod": 0,
        "cnoe": 0,
        "cnpc": 18.1,
        "cnpd": 18.1,
        "cnpa": 0,
        "cnpb": 0,
        "cnoz": 0,
        "cnox": 0,
        "cnoy": 0,
        "cnov": 0,
        "cnow": 0,
        "cnot": 0,
        "cnou": 0,
        "cnru": 0,
        "cnrv": 0,
        "cnrs": 0,
        "cnrt": 0,
        "cnrq": 0,
        "cnrr": 0,
        "cnro": 0,
        "cnrp": 0,
        "cnrm": 0,
        "cnrn": 0,
        "cnrk": 0,
        "cnrl": 0,
        "cnsf": 22.6,
        "cnsg": 19.5,
        "cnsd": 0,
        "cnse": 21.7,
        "cnsb": 0,
        "cnsc": 0,
        "cnsa": 0,
        "cnry": 0,
        "cnrz": 0,
        "cnrw": 0,
        "cnrx": 0,
        "cnqt": 0,
        "cnqu": 0,
        "cnqr": 0,
        "cnqs": 0,
        "cnqp": 0,
        "cnqq": 0,
        "cnqn": 0,
        "cnql": 0,
        "cnqj": 0,
        "cnqh": 0,
        "cnqf": 0,
        "cnqg": 1,
        "cnre": 0,
        "cnrf": 0,
        "cnrc": 0,
        "cnrd": 0,
        "cnra": 0,
        "cnrb": 0,
        "cnqz": 0,
        "cnqx": 0,
        "cnqy": 0,
        "cnqv": 0,
        "cnqw": 0,
        "cntw": 0,
        "cntx": 0,
        "cntu": 0,
        "cntv": 0,
        "cntq": 0,
        "cnto": 1,
        "cntp": 0,
        "cntn": 0,
        "cntk": 0,
        "cnuh": 0,
        "cnui": 0,
        "cnug": 0,
        "cnud": 0,
        "cnue": 0,
        "cnub": 0,
        "cnua": 0,
        "cnty": 0,
        "cntz": 0,
        "cnsl": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cnsj": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cnsk": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cnsh": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cnsi": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cnvy": 0,
        "cnvz": 0,
        "cnvw": 0,
        "cnvx": 0,
        "cnvu": 0,
        "cnvv": 0,
        "cnvs": 0,
        "cnvt": 0,
        "cnvq": 0,
        "cnvr": 0,
        "cnvo": 0,
        "cnvp": 0,
        "cnvm": 0,
        "cnvn": 0,
        "cnvk": 0,
        "cnvl": 0,
        "cnwj": 0,
        "cnwk": 0,
        "cnwh": 0,
        "cnwi": 0,
        "cnwf": 0,
        "cnwg": 0,
        "cnwd": 0,
        "cnwe": 0,
        "cnwb": 0,
        "cnwc": 0,
        "cnwa": 0,
        "cnux": 0,
        "cnuy": 0,
        "cnuv": 0,
        "cnuw": 0,
        "cnut": 0,
        "cnuu": 0,
        "cnur": 0,
        "cnus": 0,
        "cnup": 0,
        "cnuq": 0,
        "cnun": 0,
        "cnuo": 0,
        "cnul": 0,
        "cnum": 0,
        "cnuj": 0,
        "cnuk": 0,
        "cnvi": 0,
        "cnvj": 0,
        "cnvg": 0,
        "cnvh": 0,
        "cnve": 0,
        "cnvf": 0,
        "cnvc": 0,
        "cnvd": 0,
        "cnva": 0,
        "cnvb": 0,
        "cnuz": 0,
        "cnxy": 0,
        "cnxz": 0,
        "cnxw": 0,
        "cnxx": 0,
        "cnxv": 0,
        "cnxq": 0,
        "cnxr": 0,
        "cnxo": 0,
        "cnxp": 0,
        "cnxn": 0,
        "cnyl": 0,
        "cnym": 0,
        "cnyh": 0,
        "cnyf": 0,
        "cnyg": 0,
        "cnyd": 0,
        "cnye": 0,
        "cnwz": 0,
        "cnwx": 0,
        "cnwy": 0,
        "cnwv": 0,
        "cnww": 0,
        "cnwt": 0,
        "cnwu": 0,
        "cnwr": 0,
        "cnws": 0,
        "cnwp": 0,
        "cnwq": 0,
        "cnwn": 0,
        "cnwo": 0,
        "cnwl": 0,
        "cnwm": 0,
        "cnxj": 0,
        "cnxg": 0,
        "cnxh": 0,
        "cnxe": 0,
        "cnxf": 0,
        "cnxc": 0,
        "cnxd": 0,
        "cnxa": 0,
        "cnxb": 0,
        "cnzy": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cnzz": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cnzw": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cnzx": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cnzu": 0,
        "cnzv": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cnzs": 0,
        "cnzt": 0,
        "cnzq": 0,
        "cnzr": 0,
        "cnzo": 0,
        "cnzp": 0,
        "cnyz": 0,
        "cnyx": 0,
        "cnyy": 0,
        "cnyv": 0,
        "cnyw": 0,
        "cnyt": 0,
        "cnyu": 0,
        "cnyr": 0,
        "cnys": 0,
        "cnyp": 0,
        "cnyq": 0,
        "cnyn": 0,
        "cnyo": 0,
        "cnzm": 0,
        "cnzn": 0,
        "cnzk": 0,
        "cnzl": 0,
        "cnzi": 0,
        "cnzj": 0,
        "cnzg": 0,
        "cnzh": 0,
        "cnze": 0,
        "cnzf": 0,
        "cnzc": 0,
        "cnzd": 0,
        "cnza": 0,
        "cnzb": 0,
        "cobe": 0,
        "cobc": 0,
        "coba": 0,
        "coay": 0,
        "coaz": 1,
        "cobt": 0,
        "cobu": 0,
        "cobr": 0,
        "cobs": 0,
        "cobp": 0,
        "cobq": 0,
        "cobn": 0,
        "cobo": 0,
        "cobl": 0,
        "cobm": 0,
        "cobj": 0,
        "cobk": 0,
        "cobi": 0,
        "cobg": 0,
        "coac": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "coad": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "coaa": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "coab": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "coak": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "coai": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "coaj": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "coag": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "coah": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "coae": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "coaf": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "codd": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "code": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "codb": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "codc": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "coda": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cocy": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cocz": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cocw": 0,
        "cocx": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "coce": 0,
        "cocf": 0,
        "cocd": 0,
        "cobx": 0,
        "coby": 0,
        "cobv": 0,
        "cobw": 0,
        "cocu": 0,
        "cocv": 0,
        "cocs": 0,
        "coct": 0,
        "cocq": 0,
        "cocr": 0,
        "coco": 0,
        "cocp": 0,
        "cocm": 0,
        "cocn": 0,
        "cock": 0,
        "cocl": 0,
        "coci": 0,
        "cocj": 0,
        "cocg": 0,
        "coch": 0,
        "coff": 0,
        "cofg": 0,
        "cofd": 0,
        "cofe": 0,
        "cofb": 0,
        "cofc": 0,
        "cofa": 0,
        "coez": 0,
        "cofx": 0,
        "cofy": 0,
        "cofv": 0,
        "cofw": 0,
        "coft": 0,
        "cofu": 0,
        "cofr": 0,
        "cofs": 0,
        "cofp": 0,
        "cofq": 0,
        "coeg": 0,
        "coeh": 1,
        "coed": 0,
        "coeb": 0,
        "coew": 0,
        "coex": 0,
        "coeu": 0,
        "coet": 0,
        "coeq": 0,
        "coep": 0,
        "coei": 0,
        "coej": 0,
        "cohj": 0,
        "cohk": 0,
        "cohh": 0,
        "cohi": 0,
        "cohf": 0,
        "cohg": 0,
        "cohd": 0,
        "cohe": 0,
        "cohb": 0,
        "cohc": 0,
        "coha": 0,
        "cohz": 0,
        "cohx": 0,
        "cohy": 0,
        "cohv": 0,
        "cohw": 0,
        "coht": 0,
        "cohu": 0,
        "cohr": 0,
        "cohs": 0,
        "cohp": 0,
        "cohq": 0,
        "cohn": 0,
        "coho": 0,
        "cohl": 0,
        "cohm": 0,
        "cogi": 0,
        "cogj": 0,
        "cogg": 0,
        "cogh": 0,
        "coge": 0,
        "cogf": 0,
        "cogc": 0,
        "cogd": 0,
        "coga": 0,
        "cogb": 0,
        "cofz": 0,
        "cogy": 0,
        "cogz": 0,
        "cogw": 0,
        "cogx": 0,
        "cogu": 0,
        "cogv": 0,
        "cogs": 0,
        "cogt": 0,
        "cogq": 0,
        "cogr": 0,
        "cogo": 0,
        "cogp": 0,
        "cogm": 0,
        "cogn": 0,
        "cogk": 0,
        "cogl": 0,
        "coia": 0,
        "colz": 0,
        "coku": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cokv": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "coks": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cokt": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cokq": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cokr": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "coko": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cokp": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "conp": 0,
        "conn": 0,
        "cono": 0,
        "conl": 0,
        "conm": 0,
        "conj": 0,
        "conk": 0,
        "conh": 0,
        "coni": 0,
        "cong": 0,
        "como": 0,
        "comp": 0,
        "comm": 0,
        "comn": 0,
        "comk": 0,
        "coml": 0,
        "comj": 0,
        "comh": 0,
        "comf": 0,
        "comd": 0,
        "coma": 1,
        "comb": 0,
        "comq": 0,
        "comr": 0,
        "copr": 0,
        "cops": 840,
        "copp": 0,
        "copq": 0,
        "copn": 225.6,
        "copo": 0,
        "copl": 39,
        "copm": 35.6,
        "copj": 38.2,
        "copk": 38.2,
        "coph": 35.6,
        "copi": 39,
        "copf": 23,
        "copg": 0,
        "copd": 13,
        "cope": 13,
        "coqa": 2,
        "coqb": 24,
        "copz": 2,
        "copx": 840,
        "copy": 2,
        "copv": 840,
        "copw": 840,
        "copt": 840,
        "copu": 840,
        "cooi": 41.6,
        "cooj": 39,
        "cooc": 22,
        "cood": 22.5,
        "copb": 12,
        "copc": 12,
        "copa": 25,
        "cooz": 6037,
        "cjfd": 0,
        "cjev": 0,
        "cjhi": 1,
        "cjhg": 1,
        "cjhh": 1,
        "cjhe": 1,
        "cjhf": 1,
        "cjhc": 1,
        "cjhd": 1,
        "cjha": "2.0.11",
        "cjhb": 1,
        "cjhy": 0,
        "cjhz": 1,
        "cjhw": 1,
        "cjhx": 0,
        "cjhv": 0,
        "cjhq": 0,
        "cjgz": {{index}},
        "cjjq": 0,
        "cjjr": 0,
        "cjjo": 0,
        "cjjp": 0,
        "cjjm": 0,
        "cjjn": 0,
        "cjjk": 0,
        "cjjl": 0,
        "cjji": 0,
        "cjjj": 0,
        "cjjg": 0,
        "cjjh": 0,
        "cjje": 0,
        "cjjf": 0,
        "cjkb": 0,
        "cjkc": 0,
        "cjka": 0,
        "cjjy": 0,
        "cjjz": 0,
        "cjjw": 0,
        "cjjx": 0,
        "cjju": 0,
        "cjjv": 0,
        "cjjs": 0,
        "cjjt": 0,
        "cjip": 0,
        "cjiq": 0,
        "cjio": 0,
        "cjil": 0,
        "cjim": 0,
        "cjij": 0,
        "cjii": 0,
        "cjif": 0,
        "cjie": 0,
        "cjiv": 0,
        "cjit": 0,
        "cjiu": 0,
        "cjir": 0,
        "cjis": 0,
        "cjlo": 0,
        "cjlp": 0,
        "cjlm": 0,
        "cjln": 0,
        "cjlk": 0,
        "cjll": 0,
        "cjli": 0,
        "cjlj": 0,
        "cjlg": 0,
        "cjlh": 0,
        "cjle": 0,
        "cjlf": 0,
        "cjkr": 0,
        "cjks": 0,
        "cjkp": 0,
        "cjkq": 0,
        "cjkn": 0,
        "cjko": 0,
        "cjkl": 0,
        "cjkm": 0,
        "cjkj": 0,
        "cjkk": 0,
        "cjkh": 0,
        "cjki": 0,
        "cjkf": 0,
        "cjkg": 0,
        "cjkd": 0,
        "cjke": 0,
        "cjlc": 0,
        "cjld": 0,
        "cjla": 0,
        "cjlb": 0,
        "cjkz": 0,
        "cjkx": 0,
        "cjky": 0,
        "cjkv": 0,
        "cjkw": 0,
        "cjkt": 0,
        "cjku": 0,
        "cjof": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cjog": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cjod": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cjoe": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cjpw": 0,
        "cjpu": 0,
        "cjps": 0,
        "cjpq": 0,
        "cjpo": 0,
        "cjpp": 1,
        "cjqf": 0,
        "cjqg": 0,
        "cjqd": 0,
        "cjqe": 0,
        "cjqb": 0,
        "cjqc": 0,
        "cjqa": 0,
        "cjpy": 0,
        "cjpz": 0,
        "cjoj": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cjok": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cjoh": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cjoi": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cjry": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cjrx": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cjrs": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cjrr": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cjqx": 0,
        "cjqy": 0,
        "cjqv": 0,
        "cjqw": 0,
        "cjre": 0,
        "cjrc": 0,
        "cjrd": 0,
        "cjra": 0,
        "cjrb": 0,
        "cjqz": 0,
        "cjty": 0,
        "cjtz": 0,
        "cjtw": 0,
        "cjtx": 0,
        "cjtu": 0,
        "cjtv": 0,
        "cjtt": 0,
        "cjtq": 0,
        "cjtr": 0,
        "cjto": 0,
        "cjtm": 0,
        "cjtn": 0,
        "cjul": 0,
        "cjum": 0,
        "cjuj": 0,
        "cjuk": 0,
        "cjuh": 0,
        "cjui": 0,
        "cjuf": 0,
        "cjug": 0,
        "cjud": 0,
        "cjue": 0,
        "cjub": 0,
        "cjuc": 0,
        "cjua": 0,
        "cjsx": 0,
        "cjtk": 0,
        "cjtl": 0,
        "cjti": 0,
        "cjtj": 0,
        "cjth": 0,
        "cjtc": 0,
        "cjtd": 0,
        "cjta": 0,
        "cjtb": 1,
        "cjvy": 0,
        "cjvz": 0,
        "cjvw": 0,
        "cjvx": 0,
        "cjvu": 0,
        "cjvv": 0,
        "cjvs": 0,
        "cjvt": 0,
        "cjvq": 0,
        "cjvr": 0,
        "cjvo": 0,
        "cjvp": 0,
        "cjwn": 0,
        "cjwo": 0,
        "cjwl": 0,
        "cjwm": 0,
        "cjwj": 0,
        "cjwk": 0,
        "cjwh": 0,
        "cjwi": 0,
        "cjwf": 0,
        "cjwg": 0,
        "cjwd": 0,
        "cjwe": 0,
        "cjwb": 0,
        "cjwc": 0,
        "cjwa": 0,
        "cjuz": 0,
        "cjux": 0,
        "cjuy": 0,
        "cjuv": 0,
        "cjuw": 0,
        "cjut": 0,
        "cjuu": 0,
        "cjur": 0,
        "cjus": 0,
        "cjup": 0,
        "cjuq": 0,
        "cjun": 0,
        "cjuo": 0,
        "cjvm": 0,
        "cjvn": 0,
        "cjvk": 0,
        "cjvl": 0,
        "cjvi": 0,
        "cjvj": 0,
        "cjvg": 0,
        "cjvh": 0,
        "cjve": 0,
        "cjvf": 0,
        "cjvc": 0,
        "cjvd": 0,
        "cjva": 0,
        "cjvb": 0,
        "cjya": 0,
        "cjxy": 0,
        "cjxz": 0,
        "cjxu": 0,
        "cjxs": 0,
        "cjxt": 0,
        "cjxq": 0,
        "cjxr": 0,
        "cjyp": 0,
        "cjyq": 0,
        "cjyn": 0,
        "cjyo": 0,
        "cjyl": 0,
        "cjym": 0,
        "cjyj": 0,
        "cjyk": 0,
        "cjyh": 0,
        "cjyi": 0,
        "cjyf": 0,
        "cjyg": 0,
        "cjyd": 0,
        "cjye": 0,
        "cjyb": 0,
        "cjyc": 0,
        "cjww": 0,
        "cjwt": 0,
        "cjwu": 0,
        "cjwr": 0,
        "cjws": 0,
        "cjwp": 0,
        "cjwq": 0,
        "cjxm": 0,
        "cjxk": 0,
        "cjxl": 0,
        "cjxi": 0,
        "cjxj": 0,
        "cjxe": 0,
        "cjxc": 0,
        "cjxd": 0,
        "cjxa": 0,
        "cjxb": 0,
        "cjzw": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cjzx": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cjzu": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cjzv": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cjzs": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cjzt": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cjza": 0,
        "cjzb": 0,
        "cjyz": 0,
        "cjyx": 0,
        "cjyy": 0,
        "cjyv": 0,
        "cjyw": 0,
        "cjyt": 0,
        "cjyu": 0,
        "cjyr": 0,
        "cjys": 0,
        "cjzq": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cjzr": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cjzo": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cjzp": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cjzm": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cjzn": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cjzk": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cjzl": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cjzi": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cjzj": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "cjzg": 0,
        "cjzh": 0,
        "cjze": 0,
        "cjzf": 0,
        "cjzc": 0,
        "cjzd": 0,
        "ckbh": 0,
        "ckbi": 0,
        "ckbf": 0,
        "ckbg": 0,
        "ckbd": 0,
        "ckbe": 0,
        "ckbb": 0,
        "ckbc": 0,
        "ckba": 0,
        "ckay": 0,
        "ckaz": 0,
        "ckbx": 0,
        "ckby": 0,
        "ckbv": 0,
        "ckbw": 0,
        "ckbt": 0,
        "ckbu": 0,
        "ckbr": 0,
        "ckbs": 0,
        "ckbq": 0,
        "ckbl": 0,
        "ckbj": 0,
        "ckbk": 0,
        "ckaw": 0,
        "ckax": 0,
        "ckav": 0,
        "ckat": 0,
        "ckar": 0,
        "ckap": 0,
        "ckam": 1,
        "ckan": 0,
        "ckal": 0,
        "ckdz": 0,
        "ckdv": 0,
        "ckdw": 0,
        "ckdt": 0,
        "ckdu": 1,
        "ckdq": 0,
        "ckci": 0,
        "ckcj": 0,
        "ckcg": 0,
        "ckch": 0,
        "ckce": 0,
        "ckcf": 0,
        "ckcc": 0,
        "ckcd": 0,
        "ckca": 0,
        "ckcb": 0,
        "ckbz": 0,
        "ckcq": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "ckcr": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "ckco": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "ckcp": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "ckcm": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "ckcn": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "ckck": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "ckcl": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "ckfl": 0,
        "ckfm": 0,
        "ckfj": 0,
        "ckfk": 0,
        "ckfh": 0,
        "ckfi": 0,
        "ckff": 0,
        "ckfg": 0,
        "ckfd": 0,
        "ckfe": 0,
        "ckfb": 0,
        "ckfc": 0,
        "ckfa": 0,
        "ckfz": 0,
        "ckfx": 0,
        "ckfy": 0,
        "ckfv": 0,
        "ckfw": 0,
        "ckft": 0,
        "ckfu": 0,
        "ckfr": 0,
        "ckfs": 0,
        "ckfp": 0,
        "ckfq": 0,
        "ckfn": 0,
        "ckfo": 0,
        "ckek": 0,
        "ckej": 0,
        "ckeg": 0,
        "ckeh": 0,
        "ckee": 0,
        "ckef": 0,
        "ckec": 0,
        "cked": 0,
        "ckea": 0,
        "ckeb": 0,
        "ckey": 0,
        "ckez": 0,
        "ckew": 0,
        "ckex": 0,
        "ckeu": 0,
        "ckev": 0,
        "ckes": 0,
        "cket": 0,
        "ckeq": 0,
        "cker": 0,
        "ckeo": 0,
        "ckep": 0,
        "ckem": 0,
        "cken": 0,
        "ckhn": 0,
        "ckhl": 0,
        "ckhm": 0,
        "ckhj": 0,
        "ckhk": 0,
        "ckhh": 0,
        "ckhi": 0,
        "ckhf": 0,
        "ckhg": 0,
        "ckhd": 0,
        "ckhe": 0,
        "ckhb": 0,
        "ckhc": 0,
        "ckha": 0,
        "ckhx": 0,
        "ckhv": 0,
        "ckhw": 0,
        "ckht": 0,
        "ckhu": 0,
        "ckhp": 0,
        "ckgm": 0,
        "ckgn": 0,
        "ckgk": 0,
        "ckgl": 0,
        "ckgi": 0,
        "ckgj": 0,
        "ckgg": 0,
        "ckgh": 0,
        "ckge": 0,
        "ckgf": 0,
        "ckgc": 0,
        "ckgd": 0,
        "ckga": 0,
        "ckgb": 0,
        "ckgy": 0,
        "ckgz": 0,
        "ckgw": 0,
        "ckgx": 0,
        "ckgu": 0,
        "ckgv": 0,
        "ckgs": 0,
        "ckgt": 0,
        "ckgq": 0,
        "ckgr": 0,
        "ckgo": 0,
        "ckgp": 0,
        "ckjp": 0,
        "ckjq": 0,
        "ckjn": 0,
        "ckjo": 0,
        "ckjl": 0,
        "ckjm": 0,
        "ckjj": 0,
        "ckjk": 0,
        "ckjh": 0,
        "ckji": 0,
        "ckjf": 0,
        "ckjg": 0,
        "ckjd": 0,
        "ckje": 0,
        "ckjb": 0,
        "ckjc": 0,
        "ckka": 0,
        "ckkb": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "ckjz": 0,
        "ckjx": 0,
        "ckjy": 0,
        "ckjv": 0,
        "ckjw": 0,
        "ckjt": 0,
        "ckju": 0,
        "ckjr": 0,
        "ckjs": 0,
        "ckim": 0,
        "ckin": 0,
        "ckik": 0,
        "ckil": 0,
        "ckij": 0,
        "ckie": 0,
        "ckif": 0,
        "ckic": 0,
        "ckid": 0,
        "ckib": 0,
        "ckja": 0,
        "ckiy": 0,
        "ckiz": 0,
        "ckiw": 0,
        "ckix": 0,
        "ckiu": 0,
        "ckiv": 0,
        "ckis": 0,
        "ckit": 0,
        "ckir": 0,
        "cklr": 0,
        "ckls": 0,
        "cklp": 0,
        "cklq": 0,
        "cklo": 0,
        "cklm": 0,
        "cklk": 0,
        "ckli": 0,
        "cklf": 1,
        "cklg": 0,
        "ckle": 0,
        "ckmc": 0,
        "ckmd": 0,
        "ckma": 0,
        "ckmb": 0,
        "cklz": 0,
        "cklx": 0,
        "ckly": 0,
        "cklv": 0,
        "cklw": 0,
        "cklt": 0,
        "cklu": 0,
        "ckkq": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "ckko": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "ckkp": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "ckkm": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "ckkn": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "ckkk": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "ckkl": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "ckki": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "ckkj": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "ckkg": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "ckkh": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "ckke": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "ckkf": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "ckkc": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}},
        "ckkd": {{Math.Round(rnd.Next(100, 300) * 0.1, 2)}}
    },
    "data_sDeviceNo": 20,
    "frame_num": {{index}},
    "line_id": 6,
    "line_num": "6",
    "message_type": 5025,
    "netLink_flag": 0,
    "next_station": 2,
    "ocs_time": "{{DateTime.Now:yyMMddHHmmss}}",
    "sDevice": 40,
    "sDeviceTime": "{{DateTime.Now:yyMMddHHmmss}}",
    "second_circle": 0,
    "speed": 0,
    "start_station": 2,
    "terminal_station": 24,
    "train_id": 37,
    "train_name": "06037",
    "train_num": 37,
    "train_type": "B",
    "ttype_id": 10,
    "train_status": 2,
    "sDeviceTimeStamp": 1765516404000
}
"""";


var config = new ProducerConfig
{
    BootstrapServers = "10.100.0.113:9092",
};




using (var producer = new ProducerBuilder<Null, string>(config).Build())
{
    int m = 1;
    while (true)
    {
        var result = await producer.ProduceAsync("nb6-subsystem-zx", new Message<Null, string> { Value = JsonSerializer.Serialize(JsonSerializer.Deserialize<dynamic>(kafka.Invoke(m), options), options) });
        Console.WriteLine(result.Message);
        m++;
        m = m > 65535 ? 1 : m;
        Thread.Sleep(TimeSpan.FromSeconds(1));
    }

}